include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-raw-types: false

  errors:
    dead_code: error
    unused_element: error
    missing_required_param: error
    omit_local_variable_types: ignore
    include_file_not_found: ignore
    # name of fixtures in uppercase break this rule
    non_constant_identifier_names: ignore
    unnecessary_import: error
    unused_local_variable: error
    avoid_redundant_argument_values: warning
    prefer_const_constructors: warning
    cascade_invocations: warning    
    use_decorated_box: warning
    sized_box_for_whitespace: warning
    unnecessary_to_list_in_spreads: warning
    unnecessary_null_in_if_null_operators: warning
    

  exclude:  
    - lib/**.gr.dart
    - lib/**.g.dart

linter:
  rules:    
    avoid_field_initializers_in_const_classes: true
    avoid_void_async: true
    unawaited_futures: true
    cast_nullable_to_non_nullable: true
    use_super_parameters: true
    avoid_function_literals_in_foreach_calls: false
    constant_identifier_names: false
    overridden_fields: false
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false # TODO regle importante a activer des que possible !
    unnecessary_breaks: true
    invalid_case_patterns: true
    type_literal_in_constant_pattern: true
    no_literal_bool_comparisons: true
    avoid_redundant_argument_values: true
    prefer_const_constructors: true
    cascade_invocations: true 
    use_decorated_box: true
    sized_box_for_whitespace: true
    unnecessary_to_list_in_spreads: true
    unnecessary_null_in_if_null_operators: true


