name: flutter_dart_3
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.13.8

dependencies:
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
